ALTER TABLE productos ADD COLUMN IF NOT EXISTS marca VARCHAR(100);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS descuento NUMERIC(5,2) DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
UPDATE productos SET marca = 'Sin marca' WHERE marca IS NULL;
UPDATE productos SET descuento = 0 WHERE descuento IS NULL;
